import "server-only";

/**
 * Helpers for reading village-boundary dropdown + GeoJSON files.
 * SERVER-ONLY. Importing this from a client component throws at build time.
 *
 * Used by /api/boundary. The frontend (VillageMap) reads /data/* static
 * files directly via browser fetch — it does NOT call this module.
 *
 * Files live under /public/data — generated by scripts/build-village-data.mjs.
 *   /public/data/dropdowns/districts.json
 *   /public/data/dropdowns/talukas/<district_id>.json
 *   /public/data/dropdowns/villages/<district_id>/<taluka_id>.json
 *   /public/data/boundaries/villages/<district_id>/<taluka_id>.geojson
 */

import { promises as fs } from "node:fs";
import path from "node:path";

export interface DistrictRow {
  district_id: string;
  name_en: string;
  name_mr: string;
  lgd?: string | null;
}
export interface TalukaRow {
  taluka_id: string;
  district_id: string;
  name_en: string;
  name_mr: string;
  lgd?: string | null;
}
export interface VillageRow {
  village_id: string;
  district_id: string;
  taluka_id: string;
  name_en: string;
  name_mr: string;
  code?: string | null;
  boundary_file?: string;
}

export interface VillageFeature {
  type: "Feature";
  properties: {
    district_id: string;
    taluka_id: string;
    village_id: string;
    name_en: string;
    name_mr: string;
    taluka_en: string;
    taluka_mr: string;
    district_en: string;
    district_mr: string;
    code?: string | null;
  };
  geometry: GeoJSON.Polygon | GeoJSON.MultiPolygon;
}
export interface VillageFeatureCollection {
  type: "FeatureCollection";
  features: VillageFeature[];
}

const ROOT = path.join(process.cwd(), "public", "data");

async function readJson<T>(rel: string): Promise<T> {
  const full = path.join(ROOT, rel);
  const buf = await fs.readFile(full, "utf8");
  return JSON.parse(buf) as T;
}

export async function getDistricts(): Promise<DistrictRow[]> {
  return readJson<DistrictRow[]>("dropdowns/districts.json");
}

export async function getTalukas(districtId: string): Promise<TalukaRow[]> {
  return readJson<TalukaRow[]>(`dropdowns/talukas/${districtId}.json`);
}

export async function getVillages(
  districtId: string,
  talukaId: string,
): Promise<VillageRow[]> {
  return readJson<VillageRow[]>(
    `dropdowns/villages/${districtId}/${talukaId}.json`,
  );
}

export async function getTalukaBoundary(
  districtId: string,
  talukaId: string,
): Promise<VillageFeatureCollection> {
  return readJson<VillageFeatureCollection>(
    `boundaries/villages/${districtId}/${talukaId}.geojson`,
  );
}

export async function getVillageBoundary(
  districtId: string,
  talukaId: string,
  villageId: string,
): Promise<VillageFeature | null> {
  const fc = await getTalukaBoundary(districtId, talukaId);
  return fc.features.find((f) => f.properties.village_id === villageId) ?? null;
}
