import { ImageResponse } from "next/og";

/**
 * Site-wide Open Graph / social-share image, generated by next/og (Satori).
 *
 * App Router applies this to every route's og:image + twitter:image unless a
 * page exports its own opengraph-image. Code-generated (no binary asset) so
 * it's version-controlled and easy to tweak.
 *
 * Intentionally Latin-forward: Satori needs an embedded font file to render
 * Devanagari, and the default font does not cover it. Keeping the copy in
 * Latin guarantees a correct render everywhere. To add a Marathi line later,
 * load a Noto Sans Devanagari font buffer via the `fonts` option below.
 */

export const alt =
  "PrintShubh.shop — Maharashtra land documents (7/12, 8A, village maps) on WhatsApp";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

const CHIPS = ["7/12", "8A", "Village Map", "DP / TP Map", "Property Card"];

export default function OpengraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: "linear-gradient(135deg, #1e3a8a 0%, #2563eb 60%, #1d4ed8 100%)",
          padding: "72px",
          fontFamily: "sans-serif",
          color: "white",
        }}
      >
        {/* Brand row */}
        <div style={{ display: "flex", alignItems: "center", gap: "20px" }}>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              width: "84px",
              height: "84px",
              borderRadius: "20px",
              background: "white",
              color: "#2563eb",
              fontSize: "54px",
              fontWeight: 900,
            }}
          >
            P
          </div>
          <div style={{ display: "flex", fontSize: "46px", fontWeight: 800 }}>
            <span>PrintShubh</span>
            <span style={{ color: "#bfdbfe" }}>.shop</span>
          </div>
        </div>

        {/* Headline */}
        <div style={{ display: "flex", flexDirection: "column", gap: "18px" }}>
          <div style={{ fontSize: "62px", fontWeight: 900, lineHeight: 1.1 }}>
            Maharashtra land documents,
          </div>
          <div style={{ display: "flex", fontSize: "62px", fontWeight: 900, lineHeight: 1.1 }}>
            <span>fast on </span>
            <span style={{ color: "#86efac" }}>&nbsp;WhatsApp</span>
          </div>
        </div>

        {/* Service chips */}
        <div style={{ display: "flex", flexWrap: "wrap", gap: "14px" }}>
          {CHIPS.map((c) => (
            <div
              key={c}
              style={{
                display: "flex",
                padding: "10px 22px",
                borderRadius: "999px",
                background: "rgba(255,255,255,0.16)",
                border: "1px solid rgba(255,255,255,0.35)",
                fontSize: "28px",
                fontWeight: 700,
              }}
            >
              {c}
            </div>
          ))}
        </div>

        {/* Footer line */}
        <div style={{ display: "flex", fontSize: "26px", color: "#dbeafe", fontWeight: 600 }}>
          Private assistance · based on official sources · price upfront, no hidden fees
        </div>
      </div>
    ),
    { ...size },
  );
}
